version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - server-net

  app:
#    Uncomment the following line and comment the build line to use the prebuilt image
#    image: omarmokhtar99/go-docker-app
    build: .
    restart: always
    env_file:
      - app/.env
    ports:
      - target: 9090
        published: 9090
    depends_on:
      - db
    networks:
      - server-net
    volumes:
      - type: volume
        source: go-docker-vol
        target: /app

networks:
  server-net:
    driver: bridge
    internal: true

volumes:
  go-docker-vol: