version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - vnet

  app:
#    Uncomment the following line and comment the build block to use the prebuilt image
#    image: omarmokhtar99/go-docker-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - "9090:9090"
    depends_on:
      - db
    networks:
      - vnet

networks:
  vnet:
    driver: bridge